Traceback (most recent call last):
  File "/project/6003007/nteo/cosmo_project/scripts/run_test.py", line 50, in <module>
    run_training(training_params, generation_params, training_restart)
  File "/home/nteo/projects/def-douglas/nteo/cosmo_project/code_model/train.py", line 92, in run_training
    model = gans[gan_version](**training_params)
  File "/home/nteo/projects/def-douglas/nteo/cosmo_project/code_model/GAN_modules.py", line 217, in __init__
    self.discriminator = models.models[f'dis_v{dis_version}'](**training_params)
  File "/home/nteo/projects/def-douglas/nteo/cosmo_project/code_model/models.py", line 137, in __init__
    n_channels = self.cnn(torch.empty(1, 1, image_size, image_size)).size(-1)
  File "/project/6003007/nteo/cosmo_project/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/project/6003007/nteo/cosmo_project/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/project/6003007/nteo/cosmo_project/venv/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
TypeError: 'NoneType' object is not callable